<?php

use App\Http\Controllers\NewsController;
use App\Http\Controllers\Auth\AuthenticatedSessionController;
use Illuminate\Support\Facades\Route;

// Login Page (welcome.blade.php as login)
Route::get('/', [AuthenticatedSessionController::class, 'create'])->name('login');

// Authenticated Routes
Route::middleware('auth')->group(function () {
    Route::get('/news', [NewsController::class, 'index'])->name('news.index');
});

// Authentication Routes (Generated by Breeze)
require __DIR__.'/auth.php';
