<?php

use App\Http\Controllers\NewsController;
use App\Http\Controllers\Auth\AuthenticatedSessionController;
use Illuminate\Support\Facades\Route;

// Show Login Page (welcome.blade.php as login page)
Route::get('/', [AuthenticatedSessionController::class, 'create'])->name('login');

// Authenticated Routes (Only accessible after login)
Route::middleware('auth')->group(function () {
    Route::get('/news', [NewsController::class, 'index'])->name('news.index');
});

// Authentication Routes (Generated by Breeze)
// This will include routes like /login, /register, and /logout
require __DIR__.'/auth.php';
